config/routes.rb
Rails.application.routes.draw do
  resources :emotions
  resources :occasions
  resources :giftmojis
  resources :users
  resources :sessions

  resources :users, only: [:show] do 
  	resources :giftmojis, only: [:show, :index, :new]
  end 

get '/most_giftmojis' => 'users#most_giftmojis'
get '/users/:id' => 'users#show'
get '/' =>"application#index"
get '/signup' => 'users#new'
get 'login', to: 'sessions#new'
post '/login' => 'sessions#create'
get  '/logout' => 'sessions#destroy'
post '/logout' => 'sessions#destroy'

get '/auth/facebook/callback' => 'sessions#create'

post '/giftmoji/:id/buy' => 'users#update'

  #Nested resource for (Occasion - Gimojis)
 # resources :occasions, only [:show, :index] do 
 #   resources :giftmojis, only [:show, :index]
 # end 

  #Nested resource (User -> Gimojis) ??
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
		has_secure_password
         has_many :giftmojis
         has_many :giftmoji_emotions, through: :giftmojis 
         has_many :emotions, through: :giftmoji_emotions
         has_many :occasions, through: :giftmojis
         validates :fullname, presence: true 
         validates :username, uniqueness: true
         validates :uid, presence: true, unless: :password
  		 validates :password, presence: true, unless: :uid

    def buy(giftmoji)
		if self.giftcoins > giftmoji.price
			self.giftcoins -= giftmoji.price 
			giftmoji.user_id = self.id 
			giftmoji.save 
			self.save 
			"You have successfully bought the #{giftmoji.name} Giftmoji"
		else 
			"You don't have any enough giftcoins to purchase this Giftmoji"
		end 
	end 


	def self.most_giftmojis
		User.joins(:giftmojis).group("giftmojis.id").order("count(giftmojis.id) DESC").limit(1).pluck(:fullname)[0]
	end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
        @user = User.new
    end 
    
    def create 
        #binding.pry
        @user= User.create(user_params)
        session[:user_id]= @user.id
        if @user
        redirect_to "/users/#{@user.id}"
        end
    end 

	def index
        @users = User.all
    end 


    def show 
        if !!session[:user_id]
            #binding.pry
             @user = User.find_by_id(params[:id])
            respond_to do |format|
                format.json {render json: @user}
                format.html
            end 
        else 
            flash[:message] = "You are not logged in, please login."
            redirect_to '/'
        end
    end 

    def update
        @user = User.find_by_id(session[:user_id])
        if params[:giftmoji][:id]
            #binding.pry
            @giftmoji = Giftmoji.find_by_id(params[:giftmoji][:id])
            @user.buy(@giftmoji)
            #binding.pry 
            @user.save
            flash[:message] = "You have successfully purchased the #{@giftmoji.name} Giftmoji."
        end  
        
        redirect_to "/users/#{@user.id}"
    end 

    private 

    def user_params 
        params.require(:user).permit(:fullname, :username, :password, :giftcoins, :admin, :email, :password_confirmation)
    end 

end

app/helpers/users_helper.rb
module UsersHelper
    include Rails.application.routes.url_helpers

	def user_admin?
        #binding.pry
        if session[:user_id]
            @current_user = User.find_by_id(session[:user_id])
            @current_user.admin
        end 
    end 

    def logged_in?
    	session[:user_id]
    end 

    def current_user?
        session[:user_id] == params[:id]
    end

    def user_name
    	User.find_by_id(session[:user_id]).fullname
    end 

    class << self 
    end 
end

app/views/users/index.html.erb
<div class="info">
<% @users.each do |user| %>
<p><%= link_to user.username, user_path(user) %>
Name: <%= user.fullname %> -
<% if user_admin? %>
Giftcoins Balance: <%= user.giftcoins %>
<% end %>
</p><% end %>
</div>

app/views/users/most_giftmojis.html.erb
<%= User.most_giftmojis %>

app/views/users/new.html.erb
<% if @user %>
<% if @user.errors.any? %>

<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>
<% end %>


<h2>Sign up</h2>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

    <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>


app/views/users/show.html.erb
  <div class="info">
    <% if user_admin? %>
      <p><strong>ADMIN</strong></p>
    <% end %>
    <p><strong>Name:</strong> <%= @user.fullname %></p>
    <p><strong>Username:</strong> <%= @user.username %></p>
    <% if user_admin? || current_user? %>
    <p><strong>Giftcoins Balance:</strong>  <%= @user.giftcoins %></p>
    <% end %>

    <p><strong><%= link_to "My Giftmojis", user_giftmojis_path(@user), class: "my_giftmojis_link", :data => {id: @user.id} %></strong>
<!--     <% @user.giftmojis.each do |giftmoji| %>
    <%= link_to giftmoji.name, giftmoji_path(giftmoji) %> - 
    <%end%></p> -->
    <div class="display_my_giftmojis">
    </div>
   <div class="display_my_subGiftmojis">
    </div>
    <p><%= link_to 'See all Giftmojis', giftmojis_path %></p>
    <p><strong>Emotions:</strong> <% @user.emotions.uniq.each do |emotion| %>
                                   <%= link_to emotion.name, emotion_path(emotion) %> - 
                                   <%end%></p>
    <p><%= link_to 'See all Emotions', emotions_path %></p>
    <% if user_admin? %>
    <p><%= link_to "Create new Giftmoji", new_user_giftmoji_path(@user) %></p>
    <% end %>
  </div>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
  <script type="text/javascript" charset="utf-8">
$(document).ready(function () {
  $(".my_giftmojis_link").on("click", function(e) {
    e.preventDefault();
  $(".display_my_giftmojis").empty()
    var userId = parseInt($(this).attr("data-id"))
    $.get("/users/"+userId+"/giftmojis"+".json", function(giftmojis){
      let giftmojis_list = ""
      for(let i=0;i<giftmojis.length;i++){
      let giftmo = giftmojis[i]
      let giftmo_id = giftmojis[i]["id"]
      let giftmo_name = giftmojis[i]["name"]
      let name = giftmo["name"]
$(".display_my_giftmojis").append("<a href='"+userId+"/giftmojis/"+giftmo_id+"' class='load_giftmoji' data-subid='"+giftmo_id+"'  > "+giftmo_name+"</a>"+"  -")
      }

$(".load_giftmoji").on("click", function(e) {
    e.preventDefault();
    var giftmo_subId = parseInt($(this).attr("data-subid"))
    $.get("/users/"+userId+"/giftmojis/"+giftmo_subId+".json", function(subGiftmo){
  $(".display_my_subGiftmojis").empty()
  $(".display_my_subGiftmojis").append("<p><strong> Name: <a href='"+userId+"/giftmojis/"+giftmo_subId+"'>"+subGiftmo["name"]+"</a></strong></p>")
  $(".display_my_subGiftmojis").append("<p><strong> Price: </strong>"+subGiftmo["price"]+"</p>")
  $(".display_my_subGiftmojis").append("<p><strong> Tag: </strong>"+subGiftmo["tag"]+"</p>")
    })
// $.get(this.href).done(function(resp){
//   $(".display_my_subGiftmojis").html(resp)
// })


    })

    })
   
    });
  });
// });
</script>